pipeline{
    agent
	{
		docker {
        image 'maven:3.8.1-adoptopenjdk-11'
        label 'maven381'
        args  '-v /tmp:/tmp'
    	}
	}
		
	stages{
		
		stage("Prepare Workspace") {
			steps{
			    cleanWs()
			    script{
			        env.WORKSPACE_LOCAL = sh(returnStdout: true, script: 'pwd').trim()
		        	env.BUILD_TIME = sh(returnStdout: true, script: 'date +%F-%T').trim()
			    }

		       
		        echo "Workspace set to:" + env.WORKSPACE_LOCAL
		        echo "Build time:" + env.BUILD_TIME
			}	   
    	}
    	
    	stage('Checkout Self') {
    		steps{
    			script{
				    def repoURL = 'https://github.com/SerkanGitRepo/CucumberXRay.git'
				    git branch: 'master', credentialsId: '', url: repoURL
				}	
    		}

        	
    	}
    	
    	stage('Cucumber Tests') {
    		steps{
    		    withMaven(maven: 'maven381') {
	            sh """
				cd ${env.WORKSPACE_LOCAL}
				mvn clean test -e
				"""
		        }
    		}
    	}
    	
    	stage('Expose report') {
    		steps{
    		    archive "**/cucumber.json"
        		cucumber '**/cucumber.json'
    		}
    	}
	    
	    stage('Import results to Xray') {
	    	steps{
	    	    script{
	    	        def description = "[BUILD_URL|${env.BUILD_URL}]"
			def labels = '["regression","automated_regression"]'
			def environment = "DEV"
			def testExecutionFieldId = 10602
			def testEnvironmentFieldName = "customfield_10928"
			def projectKey = "LE"
			def xrayConnectorId = '5b6b2afb-584e-4bd1-a41c-0da1ed57405d'
			def info = '''{
					"fields": {
						"project": {
						"key": "''' + projectKey + '''"
					},
					"labels":''' + labels + ''',
					"description":"''' + description + '''",
					"summary": "Automated Regression Execution @ ''' + env.BUILD_TIME + ' ' + environment + ''' " ,
					"issuetype": {
					"id": "''' + testExecutionFieldId + '''"
					},
					"''' + testEnvironmentFieldName + '''" : [
					"''' + environment + '''"
					]
					}
					}'''
	
			echo info
	
			step([$class: 'XrayImportBuilder', endpointName: '/cucumber/multipart', importFilePath: 'target/cucumber.json', importInfo: info, inputInfoSwitcher: 'fileContent', serverInstance: xrayConnectorId])
	    	    }

	    	}
			
		}
	    
	}
	
}


